### ISSUE TITLE
Downloading some mods doesn't remove them from the list of downloadables

### ISSUE THREAD

**Issue by TacticsCH** [Frityet/H3VRModInstaller#25]
I tried to install Modern Warfighter Lights and lasers as well as optics and noticed then that they aren't removed from the list when I download them. You can download them infinitely basically. They are also not added to the *Downloaded* list.

---

![image](https://user-images.githubusercontent.com/50820503/109065348-ba4e0700-76eb-11eb-9eab-d71ee4f29bd7.png)

**The mods pointed by a red arrow were installed two times.**

![image](https://user-images.githubusercontent.com/50820503/109065565-131d9f80-76ec-11eb-87b1-9d98395e9188.png)

---

However the mods seem still to install (Zip is downloaded and decompressed into virtual object folder).

**Comment by Frityet** [comment]
taters is gonna look into it, will fix!

**Comment by potatoes1286** [comment]
Fixed; Jayyden's mods were incorrectly assigned as a zip when they're a rar file :V
it downloads correctly now.
