### ISSUE TITLE
GUI version requires .NET 5.0.0 but error message tries to install 3.1

### ISSUE THREAD

**Issue by GarretPolk** [Frityet/H3VRModInstaller#3]
H3VRModInstaller version : GUI 0.4.0 prerelease

Just a heads up that the .NET dependency error message takes the user to the wrong page. I'm guessing that's coming from Microsoft, not you?

1. Unzipped app into the Steam H3VR folder.
2. Ran H3VRModInstaller.GUI.exe
3. App showed error message (see attachment) saying it needed .NET 5.0.0 with a download prompt
4. Clicked YES to download and it opened a Microsoft page to download .NET 3.1 (weird, right?)
https://dotnet.microsoft.com/download/dotnet-core/thank-you/runtime-desktop-3.1.10-windows-x64-installer
5. Downloaded and installed 3.1
6. Ran H3VRModInstaller.GUI.exe - same error message appeared (as expected)
7. Downloaded and installed the .NET Desktop 5.0.1 x64 runtime (did not need to reboot)
8. Ran H3VRModInstaller.GUI.exe - ran successfully

FYI, link to the runtime needed ("Desktop" version!)
https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-desktop-5.0.1-windows-x64-installer

![h3vr mod installer gui dot net](https://user-images.githubusercontent.com/4492649/103755628-fce44480-4fc2-11eb-9a68-bcac75685129.jpg)

**Comment by Frityet** [comment]
I see, will look into this

**Comment by Frityet** [comment]
When ModInstaller reaches V1.0, you will no longer need to install Dot Net
