### ISSUE TITLE
Simply not working

### ISSUE THREAD

**Issue by JungleBlobs** [Frityet/H3VRModInstaller#31]
So I updated this, and now, and before the update, the mod loader would not work. No matter what, the files just don't go into my game folder, and it wont detect my currently installed mods. I'm going to attempt another update/reinstall but I'm not sure whats going on.

**Comment by Frityet** [comment]
@JungleBlobs sorry for late reply, 

Did you every have multiple installations of h3vr?

**Comment by JungleBlobs** [comment]
> @JungleBlobs sorry for late reply,
> 
> Did you every have multiple installations of h3vr?

I just checked, I think I did, one on D: and one on C:. I'm uninstalling them both and reinstalling one, I'll check if that works.

**Comment by Frityet** [comment]
That is the issue, steam shits itself if there is > 1 installation of a game

**Comment by Frityet** [comment]
Assuming it is working now
