### ISSUE TITLE
Downloadable and Installed Mods list dupes after each install

### ISSUE THREAD

**Issue by KeystrokeCascade** [Frityet/H3VRModInstaller#7]
The available mods and installed mods list dupes every time you install a mod.  I suspect this is due to downloading the mod database after every install and appending it to the current one.

![image](https://user-images.githubusercontent.com/35793455/104833302-c0321a80-58eb-11eb-9d48-2af4e7bd5c77.png)

![image](https://user-images.githubusercontent.com/35793455/104833317-d0e29080-58eb-11eb-9e77-4763c0f2a2a5.png)

**Comment by Frityet** [comment]
Looked in to this and is confirmed fixed
